apiVersion: v1
kind: Service
metadata:
  name: consulcluster-nodeport
  labels:
    app: consulcluster-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    #port is loadbalancer port
    port: 8500
    # targetport is container port
    targetPort: 8500
    nodePort: 30089
  selector:
    app: consulcluster
