apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-nodeport
  labels:
    app: elasticsearch-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30014
  selector:
    app: elasticsearch-cluster
