version: '3'
services:
    elasticsearch:
      image: siangyeh8818/elasticsearch-head:v6.3.1
#      image: siangyeh8818/elasticsearch-head:v6.3-test
      container_name: elasticsearch-1
#      network_mode: host
      networks: 
        - consul-overlay
      ports:
        - "9200:9200"
        - "9300:9300"
        - "9100:9100"
      restart: always
      command: [ "elasticsearch", "-E", "node.name=172.16.106.130",
                                  "-E","cluster.name=BFOPcluster",
                                  "-E", "node.master=true",
                                  "-E", "node.data=true",
                                  "-E", "network.host=0.0.0.0",
                                  "-E", "discovery.zen.minimum_master_nodes=1",
                                  "-E", "discovery.zen.ping.unicast.hosts=172.16.106.130:9300,172.16.106.131:9300,172.16.106.132:9300"]
      logging:
        options:
          max-size: "5M"
          max-file: "10"
        driver: json-file
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        HEAD_MINUTOR_IP: 172.16.106.130
      volumes:
        - /etc/localtime:/etc/localtime
#        - ./sg_roles.yml:/usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml
#        - /home/deployer/infrastructure/volumes/elasticsearch:/usr/share/elasticsearch/data

networks:
  consul-overlay:
    driver: overlay
    ipam:
      config:
      - subnet: 10.144.10.0/24
