cluster.name: BFOPelasticsearch
node.name: "elasticsearch-3"
node.master: true
node.data: true
network.host: 172.16.106.132
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.timeout: 2
discovery.zen.ping.unicast.hosts: ["172.16.106.130", "172.16.106.131", "172.16.106.132"]
