version: '2.1'
services:
    elasticsearch:
      image: siangyeh8818/elasticsearch-head:v6.3.1
#      image: siangyeh8818/elasticsearch-head:v6.3-test
      container_name: elasticsearch-1
      network_mode: host
      ports:
        - "9200:9200"
        - "9300:9300"
        - "9100:9100"
      restart: always
      command: [ "elasticsearch", "-E", "node.name=172.16.106.130",
                                  "-E","cluster.name=BFOPcluster",
                                  "-E", "node.master=true",
                                  "-E", "node.data=true",
                                  "-E", "network.host=172.16.106.130",
                                  "-E", "discovery.zen.minimum_master_nodes=1",
                                  "-E", "discovery.zen.ping.unicast.hosts=172.16.106.130:9300,172.16.106.131:9300,172.16.106.132:9300",
                                  "-E", "http.cors.enabled=true",
                                  "-E", "http.cors.allow-origin=*"]
      logging:
        options:
          max-size: "5M"
          max-file: "10"
        driver: json-file
      ulimits:
        nproc: 65535
        nofile:
          soft: 65536
          hard: 65536
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        HEAD_MINUTOR_IP: 172.16.106.130
      volumes:
        - /etc/localtime:/etc/localtime
#        - ./sg_roles.yml:/usr/share/elasticsearch/plugins/search-guard-6/sgconfig/sg_roles.yml
#        - /home/deployer/infrastructure/volumes/elasticsearch:/usr/share/elasticsearch/data
    logstash:
      container_name: logstash
      image: logstash-oss:6.3-test
      logging:
        driver: json-file
        options:
          max-file: "10"
          max-size: "5m"
      restart: always
      environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      volumes:
      - /etc/localtime:/etc/localtime
      depends_on:
        - elasticsearch
